name: Check-Directory-Content
description: Check if directory contains the listed files.
inputs:
  files:
    description: List of filenames.
    type: string

runs:
  using: composite
  steps:
    - name: 📋 Verify extracted tarball content
      shell: bash
      run: |
        set +e

        ANSI_LIGHT_RED=$'\x1b[91m'
        ANSI_LIGHT_GREEN=$'\x1b[92m'
        ANSI_NOCOLOR=$'\x1b[0m'

        errors=0
        while IFS=$'\r\n' read -r file; do
          # skip empty or comment lines
          [[ "${file}" == "" || "${file:0:1}" == "#" ]] && continue

          printf "%s" "Checking '${file}' ... "
          if [[ -f "$file" ]]; then
            printf "%s\n" "${ANSI_LIGHT_GREEN}[PASSED]${ANSI_NOCOLOR}"
          else
            printf "%s\n" "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
            printf "%s\n" "${ANSI_LIGHT_RED}Extracted artifact doesn't contain file '${file}'.${ANSI_NOCOLOR}"
            errors=$((errors + 1))
          fi
        done <<<'${{ inputs.files }}'

        printf "%s\n" ""
        if [[ $errors -ne 0 ]]; then
          printf "%s\n" "${ANSI_LIGHT_RED}Counted ${errors} errors.${ANSI_NOCOLOR}"
          exit 1
        else
          printf "%s\n" "${ANSI_LIGHT_GREEN}No errors found.${ANSI_NOCOLOR}"
        fi
